# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sat May  2 22:05:59 2026
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrameUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrameUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1445, 929))
        self.SetTitle("frame")

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "&New Project\tCtrl+N", "")
        self.Bind(wx.EVT_MENU, self.OnBtnResetAll, item)
        wxglade_tmp_menu.Append(wx.ID_OPEN, "&Load Project...\tCtrl+L", "")
        self.Bind(wx.EVT_MENU, self.OnMenuLoad, id=wx.ID_OPEN)
        wxglade_tmp_menu.Append(wx.ID_SAVE, "&Save\tCtrl+S", "")
        self.Bind(wx.EVT_MENU, self.OnMenuSave, id=wx.ID_SAVE)
        wxglade_tmp_menu.Append(wx.ID_SAVEAS, "Save Project &As...\tCtrl+Shift+S", "")
        self.Bind(wx.EVT_MENU, self.OnMenuSaveAs, id=wx.ID_SAVEAS)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "&Import Superfish File...", "")
        self.Bind(wx.EVT_MENU, self.OnMenuImportSuperfish, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export gmesh geo file...\tCtrl+G", "")
        self.Bind(wx.EVT_MENU, self.OnBtnExportGeo, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export Python Script...\tCtrl+P", "")
        self.Bind(wx.EVT_MENU, self.OnBtnExportPythonScript, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export Superfish .af...\tCtrl+A", "")
        self.Bind(wx.EVT_MENU, self.OnBtnExportSuperfish, item)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "E&xit", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "&File")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        self.sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1_pane_1.SetBackgroundColour(wx.Colour(248, 255, 223))
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Mesh Geometry Edit")

        self.sizer_2 = wx.BoxSizer(wx.VERTICAL)

        sizer_16 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Draw Area Setting"), wx.HORIZONTAL)
        self.sizer_2.Add(sizer_16, 0, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Unit : ")
        sizer_16.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.unit_choice = wx.Choice(self.notebook_1_pane_1, wx.ID_ANY, choices=["m", "cm", "mm", "inch"])
        self.unit_choice.SetSelection(2)
        sizer_16.Add(self.unit_choice, 0, 0, 0)

        sizer_16.Add((30, 20), 0, 0, 0)

        label_9 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "X min: ")
        sizer_16.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.xmin_ctrl = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "0")
        sizer_16.Add(self.xmin_ctrl, 0, 0, 0)

        label_10 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "X max: ")
        sizer_16.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.xmax_ctrl = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "100")
        sizer_16.Add(self.xmax_ctrl, 0, 0, 0)

        label_11 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Y min: ")
        sizer_16.Add(label_11, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.ymin_ctrl = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "0")
        sizer_16.Add(self.ymin_ctrl, 0, 0, 0)

        label_12 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Y max: ")
        sizer_16.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.ymax_ctrl = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "100")
        sizer_16.Add(self.ymax_ctrl, 0, 0, 0)

        sizer_16.Add((20, 20), 0, 0, 0)

        self.update_limits_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Update Limits")
        sizer_16.Add(self.update_limits_button, 0, 0, 0)

        self.sizer_editor = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_2.Add(self.sizer_editor, 2, wx.EXPAND, 0)

        self.sizer_editor.Add((0, 0), 0, 0, 0)

        self.sizer_3 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_editor.Add(self.sizer_3, 0, wx.EXPAND, 0)

        self.sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_3.Add(self.sizer_4, 0, wx.EXPAND, 0)

        self.close_loop_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Close Loop")
        self.sizer_4.Add(self.close_loop_button, 0, 0, 0)

        self.sizer_4.Add((30, 20), 1, wx.ALL | wx.EXPAND, 0)

        self.reverse_loop_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Reverse Loop")
        self.sizer_4.Add(self.reverse_loop_button, 0, 0, 0)

        self.sizer_4.Add((150, 20), 0, 0, 0)

        self.sizer_4.Add((0, 0), 0, 0, 0)

        self.mode_radiobox = wx.RadioBox(self.notebook_1_pane_1, wx.ID_ANY, "Edit Mode", choices=["Edit Points", "Edit Lines"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.mode_radiobox.Enable(False)
        self.mode_radiobox.SetSelection(0)
        self.sizer_3.Add(self.mode_radiobox, 0, 0, 0)

        self.panel_point_edit = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY)
        self.panel_point_edit.SetBackgroundColour(wx.Colour(215, 255, 175))
        self.sizer_3.Add(self.panel_point_edit, 0, wx.ALL | wx.EXPAND, 1)

        self.sizer_point_edit = wx.StaticBoxSizer(wx.StaticBox(self.panel_point_edit, wx.ID_ANY, "Point Edit"), wx.HORIZONTAL)

        self.selected_point_label = wx.StaticText(self.panel_point_edit, wx.ID_ANY, "Selected Point -  ")
        self.sizer_point_edit.Add(self.selected_point_label, 0, wx.ALL, 5)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_point_edit.Add(sizer_6, 1, wx.EXPAND, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(sizer_7, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_point_edit, wx.ID_ANY, " X :")
        sizer_7.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.coord_x_ctrl = wx.TextCtrl(self.panel_point_edit, wx.ID_ANY, "")
        sizer_7.Add(self.coord_x_ctrl, 0, 0, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(sizer_8, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_point_edit, wx.ID_ANY, " Y :")
        sizer_8.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.coord_y_ctrl = wx.TextCtrl(self.panel_point_edit, wx.ID_ANY, "")
        sizer_8.Add(self.coord_y_ctrl, 0, 0, 0)

        self.update_coord_button = wx.Button(self.panel_point_edit, wx.ID_ANY, "Update Coords")
        sizer_6.Add(self.update_coord_button, 0, wx.ALIGN_RIGHT | wx.ALL, 5)

        self.delete_point_button = wx.Button(self.panel_point_edit, wx.ID_ANY, "Delete Point")
        self.sizer_point_edit.Add(self.delete_point_button, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.sizer_point_edit.Add((100, 20), 0, 0, 0)

        self.panel_line_edit = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY)
        self.panel_line_edit.SetBackgroundColour(wx.Colour(218, 228, 225))
        self.sizer_3.Add(self.panel_line_edit, 0, wx.ALL | wx.EXPAND, 1)

        self.sizer_line_edit = wx.StaticBoxSizer(wx.StaticBox(self.panel_line_edit, wx.ID_ANY, "Line Edit"), wx.VERTICAL)

        self.selected_line_label = wx.StaticText(self.panel_line_edit, wx.ID_ANY, "Selected Segment: -")
        self.sizer_line_edit.Add(self.selected_line_label, 0, wx.ALL, 6)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_line_edit.Add(sizer_11, 1, wx.EXPAND, 0)

        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_11.Add(sizer_10, 1, wx.EXPAND, 0)

        self.convert_to_arc_button = wx.Button(self.panel_line_edit, wx.ID_ANY, "Convert to 90deg Arc")
        sizer_10.Add(self.convert_to_arc_button, 0, 0, 0)

        self.convert_to_line_button = wx.Button(self.panel_line_edit, wx.ID_ANY, "Convert back to Line")
        sizer_10.Add(self.convert_to_line_button, 0, 0, 0)

        sizer_11.Add((20, 20), 0, 0, 0)

        label_3 = wx.StaticText(self.panel_line_edit, wx.ID_ANY, "Center ")
        sizer_11.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)

        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12.Add(sizer_13, 0, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_line_edit, wx.ID_ANY, " X :")
        sizer_13.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.center_x_ctrl = wx.TextCtrl(self.panel_line_edit, wx.ID_ANY, "")
        sizer_13.Add(self.center_x_ctrl, 0, 0, 0)

        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12.Add(sizer_14, 0, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_line_edit, wx.ID_ANY, " Y :")
        sizer_14.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.center_y_ctrl = wx.TextCtrl(self.panel_line_edit, wx.ID_ANY, "")
        sizer_14.Add(self.center_y_ctrl, 0, 0, 0)

        self.update_center_button = wx.Button(self.panel_line_edit, wx.ID_ANY, "Update Center")
        sizer_11.Add(self.update_center_button, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_line_edit.Add(sizer_15, 0, wx.ALL | wx.EXPAND, 5)

        sizer_15.Add((20, 20), 0, 0, 0)

        label_6 = wx.StaticText(self.panel_line_edit, wx.ID_ANY, "Physical Name : ")
        sizer_15.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.physical_name_ctrl = wx.ComboBox(self.panel_line_edit, wx.ID_ANY, choices=["PEC", "E-short", "M-short", "Dirichlet", "Neumann", "None"], style=wx.CB_DROPDOWN)
        sizer_15.Add(self.physical_name_ctrl, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_line_edit, wx.ID_ANY, " PEC, Dirichlet, Neumann, E-short, M-short")
        sizer_15.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.sizer_line_edit.Add((0, 0), 0, 0, 0)

        self.text_ctrl_hint_message = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "Plot initical sum points by click.", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.sizer_3.Add(self.text_ctrl_hint_message, 1, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_3.Add(sizer_5, 0, wx.EXPAND, 0)

        sizer_5.Add((100, 20), 1, wx.EXPAND, 0)

        self.reset_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Reset All")
        self.reset_button.SetBackgroundColour(wx.Colour(255, 153, 95))
        sizer_5.Add(self.reset_button, 0, wx.ALL, 5)

        sizer_17 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Output"), wx.HORIZONTAL)
        self.sizer_2.Add(sizer_17, 0, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Mesh Size (lc):")
        sizer_17.Add(label_13, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.mesh_size_ctrl = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "5")
        self.mesh_size_ctrl.SetMinSize((80, 23))
        sizer_17.Add(self.mesh_size_ctrl, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_17.Add((20, 20), 0, 0, 0)

        self.radio_box_mesh_order = wx.RadioBox(self.notebook_1_pane_1, wx.ID_ANY, "Mesh order", choices=["1st", "2nd"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.radio_box_mesh_order.SetSelection(1)
        sizer_17.Add(self.radio_box_mesh_order, 0, 0, 0)

        sizer_17.Add((50, 20), 0, 0, 0)

        self.export_geo_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Export to .geo")
        sizer_17.Add(self.export_geo_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_17.Add((20, 20), 0, 0, 0)

        self.export_msh_direct_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Export MSH (Direct)")
        sizer_17.Add(self.export_msh_direct_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_17.Add((20, 20), 0, 0, 0)

        self.export_py_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Export Python Script")
        sizer_17.Add(self.export_py_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_17.Add((20, 20), 0, 0, 0)

        self.export_superfish_button = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Export Superfish")
        sizer_17.Add(self.export_superfish_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, "FEM Analysis")

        self.sizer_fem_main = wx.BoxSizer(wx.VERTICAL)

        sizer_fem_solver = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_2, wx.ID_ANY, "Solver Settings"), wx.VERTICAL)
        self.sizer_fem_main.Add(sizer_fem_solver, 0, wx.ALL | wx.EXPAND, 5)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_solver.Add(sizer_18, 0, wx.EXPAND, 0)

        label_mesh_file = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Mesh File:")
        sizer_18.Add(label_mesh_file, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.fem_mesh_path_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "")
        sizer_18.Add(self.fem_mesh_path_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.btn_browse_mesh = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Browse...")
        sizer_18.Add(self.btn_browse_mesh, 0, wx.ALL, 5)

        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_solver.Add(sizer_23, 1, wx.EXPAND, 0)

        self.radio_box_analysis_mode = wx.RadioBox(self.notebook_1_pane_2, wx.ID_ANY, "Analysis Mode", choices=["TM0", "HOM"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.radio_box_analysis_mode.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        self.radio_box_analysis_mode.SetSelection(0)
        sizer_23.Add(self.radio_box_analysis_mode, 0, wx.ALL, 5)

        label_hom_order = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Mode Orders (e.g. 0 1 2):")
        sizer_23.Add(label_hom_order, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.hom_order_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "0 1")
        self.hom_order_ctrl.Enable(False)
        sizer_23.Add(self.hom_order_ctrl, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_23.Add((20, 20), 0, 0, 0)

        self.radio_mesh_order = wx.RadioBox(self.notebook_1_pane_2, wx.ID_ANY, "Mesh Order", choices=["1st Order", "2nd Order"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.radio_mesh_order.SetSelection(1)
        sizer_23.Add(self.radio_mesh_order, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_23.Add((0, 0), 0, 0, 0)

        sizer_23.Add((0, 0), 0, 0, 0)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_solver.Add(sizer_9, 0, wx.EXPAND, 0)

        self.fem_wave_type_radio = wx.RadioBox(self.notebook_1_pane_2, wx.ID_ANY, "Wave Type", choices=["Standing Wave", "Traveling Wave"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.fem_wave_type_radio.SetSelection(0)
        sizer_9.Add(self.fem_wave_type_radio, 0, wx.ALL, 5)

        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_24, 0, wx.EXPAND, 0)

        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24.Add(sizer_25, 0, wx.EXPAND, 0)

        label_phase = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Phase Shift (deg):")
        sizer_25.Add(label_phase, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.fem_phase_shift_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "120.0")
        self.fem_phase_shift_ctrl.SetMinSize((150, 23))
        self.fem_phase_shift_ctrl.Enable(False)
        sizer_25.Add(self.fem_phase_shift_ctrl, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        label_16 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "(e.g. \"120\", \"60,90,120\", \"0:180:20\")")
        sizer_24.Add(label_16, 0, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 5)

        sizer_9.Add((20, 20), 0, 0, 0)

        label_modes = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Number of Modes:")
        sizer_9.Add(label_modes, 0, wx.ALIGN_BOTTOM | wx.ALL, 3)

        self.num_modes_ctrl = wx.SpinCtrl(self.notebook_1_pane_2, wx.ID_ANY, "10", min=1, max=100)
        sizer_9.Add(self.num_modes_ctrl, 0, wx.ALIGN_BOTTOM | wx.ALL, 3)

        sizer_9.Add((30, 20), 0, 0, 0)

        self.btn_run_solver = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Run Solver")
        self.btn_run_solver.SetBackgroundColour(wx.Colour(175, 216, 255))
        self.btn_run_solver.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        sizer_9.Add(self.btn_run_solver, 0, wx.ALIGN_BOTTOM | wx.LEFT | wx.RIGHT, 5)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_fem_post = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_2, wx.ID_ANY, "Post-Process Settings"), wx.VERTICAL)
        self.sizer_fem_main.Add(sizer_fem_post, 0, wx.ALL | wx.EXPAND, 5)

        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_20, 0, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Raw Result File: ")
        sizer_20.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.fem_raw_result_path_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "")
        sizer_20.Add(self.fem_raw_result_path_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.btn_browse_raw_result = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Browse...")
        sizer_20.Add(self.btn_browse_raw_result, 0, wx.ALL, 5)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_19, 0, wx.EXPAND, 0)

        label_cond = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Conductivity [S/m]:")
        sizer_19.Add(label_cond, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.fem_conductivity_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "5.8e7")
        sizer_19.Add(self.fem_conductivity_ctrl, 0, wx.ALL, 5)

        label_beta = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Beta (v/c):")
        sizer_19.Add(label_beta, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        self.fem_beta_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "1.0")
        sizer_19.Add(self.fem_beta_ctrl, 0, wx.ALL, 5)

        self.btn_run_post = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Run Post-Process")
        self.btn_run_post.SetBackgroundColour(wx.Colour(255, 211, 127))
        self.btn_run_post.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        sizer_19.Add(self.btn_run_post, 0, wx.ALL, 5)

        sizer_19.Add((0, 0), 0, 0, 0)

        sizer_19.Add((0, 0), 0, 0, 0)

        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_21, 1, wx.EXPAND, 0)

        label_15 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, "Post-Processed Result File: ")
        sizer_21.Add(label_15, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.fem_processed_result_path_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "")
        sizer_21.Add(self.fem_processed_result_path_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.btn_browse_processed_result = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Browse...")
        sizer_21.Add(self.btn_browse_processed_result, 0, wx.ALL, 5)

        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_22, 0, wx.EXPAND, 0)

        self.btn_view_results = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Result Viewer")
        self.btn_view_results.SetBackgroundColour(wx.Colour(184, 254, 220))
        self.btn_view_results.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        sizer_22.Add(self.btn_view_results, 0, wx.ALL, 5)

        sizer_22.Add((50, 20), 0, 0, 0)

        self.btn_create_report = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Create HTML Report")
        sizer_22.Add(self.btn_create_report, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.checkbox_report_anim = wx.CheckBox(self.notebook_1_pane_2, wx.ID_ANY, "Create animation")
        sizer_22.Add(self.checkbox_report_anim, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_22.Add((20, 20), 0, 0, 0)

        self.btn_open_report = wx.Button(self.notebook_1_pane_2, wx.ID_ANY, "Open HTML Report")
        sizer_22.Add(self.btn_open_report, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_22.Add((0, 0), 0, 0, 0)

        self.fem_log_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.fem_log_ctrl.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.fem_log_ctrl.SetForegroundColour(wx.Colour(255, 255, 255))
        self.fem_log_ctrl.SetFont(wx.Font(10, wx.FONTFAMILY_MODERN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Consolas"))
        self.sizer_fem_main.Add(self.fem_log_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.notebook_1_pane_2.SetSizer(self.sizer_fem_main)

        self.panel_line_edit.SetSizer(self.sizer_line_edit)

        self.panel_point_edit.SetSizer(self.sizer_point_edit)

        self.notebook_1_pane_1.SetSizer(self.sizer_2)

        self.panel_1.SetSizer(self.sizer_1)

        self.Layout()

        self.Bind(wx.EVT_CHOICE, self.on_unit_change, self.unit_choice)
        self.Bind(wx.EVT_BUTTON, self.OnBtnUpdateLimits, self.update_limits_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnCloseLoop, self.close_loop_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnReverseLoop, self.reverse_loop_button)
        self.Bind(wx.EVT_RADIOBOX, self.on_mode_change, self.mode_radiobox)
        self.Bind(wx.EVT_BUTTON, self.OnBtnUpdateCoord, self.update_coord_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnDeletePoint, self.delete_point_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnConvertToArc, self.convert_to_arc_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnConvetToLine, self.convert_to_line_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnUpdateCenter, self.update_center_button)
        self.Bind(wx.EVT_COMBOBOX, self.on_physical_name_change, self.physical_name_ctrl)
        self.Bind(wx.EVT_TEXT, self.on_physical_name_change, self.physical_name_ctrl)
        self.Bind(wx.EVT_BUTTON, self.OnBtnResetAll, self.reset_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnExportGeo, self.export_geo_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnExportMshDirect, self.export_msh_direct_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnExportPythonScript, self.export_py_button)
        self.Bind(wx.EVT_BUTTON, self.OnBtnExportSuperfish, self.export_superfish_button)
        self.Bind(wx.EVT_BUTTON, self.OnBrowseMesh, self.btn_browse_mesh)
        self.Bind(wx.EVT_RADIOBOX, self.on_radio_box_analysis_mode, self.radio_box_analysis_mode)
        self.Bind(wx.EVT_RADIOBOX, self.on_fem_wave_type_radio, self.fem_wave_type_radio)
        self.Bind(wx.EVT_BUTTON, self.OnRunSolver, self.btn_run_solver)
        self.Bind(wx.EVT_BUTTON, self.OnBrowseRawResult, self.btn_browse_raw_result)
        self.Bind(wx.EVT_BUTTON, self.OnRunPost, self.btn_run_post)
        self.Bind(wx.EVT_BUTTON, self.OnBrowseProcessedResult, self.btn_browse_processed_result)
        self.Bind(wx.EVT_BUTTON, self.OnViewResults, self.btn_view_results)
        self.Bind(wx.EVT_BUTTON, self.OnBtnCreateReport, self.btn_create_report)
        self.Bind(wx.EVT_BUTTON, self.OnOpenReport, self.btn_open_report)
        # end wxGlade

    def OnBtnResetAll(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnResetAll' not implemented!")
        event.Skip()

    def OnMenuLoad(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuLoad' not implemented!")
        event.Skip()

    def OnMenuSave(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuSave' not implemented!")
        event.Skip()

    def OnMenuSaveAs(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuSaveAs' not implemented!")
        event.Skip()

    def OnMenuImportSuperfish(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuImportSuperfish' not implemented!")
        event.Skip()

    def OnBtnExportGeo(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnExportGeo' not implemented!")
        event.Skip()

    def OnBtnExportPythonScript(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnExportPythonScript' not implemented!")
        event.Skip()

    def OnBtnExportSuperfish(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnExportSuperfish' not implemented!")
        event.Skip()

    def on_unit_change(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_unit_change' not implemented!")
        event.Skip()

    def OnBtnUpdateLimits(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnUpdateLimits' not implemented!")
        event.Skip()

    def OnBtnCloseLoop(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnCloseLoop' not implemented!")
        event.Skip()

    def OnBtnReverseLoop(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnReverseLoop' not implemented!")
        event.Skip()

    def on_mode_change(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_mode_change' not implemented!")
        event.Skip()

    def OnBtnUpdateCoord(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnUpdateCoord' not implemented!")
        event.Skip()

    def OnBtnDeletePoint(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnDeletePoint' not implemented!")
        event.Skip()

    def OnBtnConvertToArc(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnConvertToArc' not implemented!")
        event.Skip()

    def OnBtnConvetToLine(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnConvetToLine' not implemented!")
        event.Skip()

    def OnBtnUpdateCenter(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnUpdateCenter' not implemented!")
        event.Skip()

    def on_physical_name_change(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_physical_name_change' not implemented!")
        event.Skip()

    def OnBtnExportMshDirect(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnExportMshDirect' not implemented!")
        event.Skip()

    def OnBrowseMesh(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBrowseMesh' not implemented!")
        event.Skip()

    def on_radio_box_analysis_mode(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_radio_box_analysis_mode' not implemented!")
        event.Skip()

    def on_fem_wave_type_radio(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_fem_wave_type_radio' not implemented!")
        event.Skip()

    def OnRunSolver(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnRunSolver' not implemented!")
        event.Skip()

    def OnBrowseRawResult(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBrowseRawResult' not implemented!")
        event.Skip()

    def OnRunPost(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnRunPost' not implemented!")
        event.Skip()

    def OnBrowseProcessedResult(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBrowseProcessedResult' not implemented!")
        event.Skip()

    def OnViewResults(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnViewResults' not implemented!")
        event.Skip()

    def OnBtnCreateReport(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnCreateReport' not implemented!")
        event.Skip()

    def OnOpenReport(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnOpenReport' not implemented!")
        event.Skip()

# end of class MyFrameUI
