# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sat May  2 22:05:59 2026
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ResultViewerUI(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ResultViewerUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((1017, 763))
        self.SetTitle("dialog")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "High Order Mode n: ")
        sizer_3.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.choice_HOM_n = wx.Choice(self, wx.ID_ANY, choices=["0"])
        self.choice_HOM_n.SetSelection(0)
        sizer_3.Add(self.choice_HOM_n, 0, 0, 0)

        sizer_3.Add((20, 20), 0, 0, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, "Mode: ")
        sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.choice_mode = wx.Choice(self, wx.ID_ANY, choices=["0"])
        self.choice_mode.SetSelection(0)
        sizer_3.Add(self.choice_mode, 0, 0, 0)

        sizer_3.Add((20, 20), 0, 0, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, "Sim. Phase Shift")
        sizer_3.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.choice_sim_phase = wx.Choice(self, wx.ID_ANY, choices=["0"])
        self.choice_sim_phase.SetSelection(0)
        sizer_3.Add(self.choice_sim_phase, 0, 0, 0)

        sizer_3.Add((20, 20), 0, 0, 0)

        label_7 = wx.StaticText(self, wx.ID_ANY, "Time Phase: ")
        sizer_3.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.spin_ctrl_time_phase = wx.SpinCtrl(self, wx.ID_ANY, "0", min=0, max=360)
        sizer_3.Add(self.spin_ctrl_time_phase, 0, 0, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 0, wx.EXPAND, 0)

        self.checkbox_H_theta = wx.CheckBox(self, wx.ID_ANY, "H_theta (Color)")
        self.checkbox_H_theta.SetValue(1)
        sizer_4.Add(self.checkbox_H_theta, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_4.Add((20, 20), 0, 0, 0)

        self.checkbox_E_lines = wx.CheckBox(self, wx.ID_ANY, "E Lins")
        self.checkbox_E_lines.SetValue(1)
        sizer_4.Add(self.checkbox_E_lines, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, " Levels: ")
        sizer_4.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.spin_ctrl_E_line_levels = wx.SpinCtrl(self, wx.ID_ANY, "20", min=0, max=300)
        sizer_4.Add(self.spin_ctrl_E_line_levels, 0, 0, 0)

        sizer_4.Add((20, 20), 0, 0, 0)

        self.checkbox_vectors = wx.CheckBox(self, wx.ID_ANY, "Vectors")
        sizer_4.Add(self.checkbox_vectors, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_5 = wx.StaticText(self, wx.ID_ANY, " z:")
        sizer_4.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.spin_ctrl_vectors_z = wx.SpinCtrl(self, wx.ID_ANY, "20", min=0, max=500)
        sizer_4.Add(self.spin_ctrl_vectors_z, 0, 0, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, " r:")
        sizer_4.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.spin_ctrl_vectors_r = wx.SpinCtrl(self, wx.ID_ANY, "20", min=0, max=500)
        sizer_4.Add(self.spin_ctrl_vectors_r, 0, 0, 0)

        sizer_4.Add((20, 20), 0, 0, 0)

        self.checkbox_show_mesh = wx.CheckBox(self, wx.ID_ANY, "Show Mesh")
        sizer_4.Add(self.checkbox_show_mesh, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_4.Add((20, 20), 0, 0, 0)

        self.checkbox_e_wall = wx.CheckBox(self, wx.ID_ANY, "Show Mesh")
        sizer_4.Add(self.checkbox_e_wall, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.panel_graph = wx.Panel(self, wx.ID_ANY)
        sizer_1.Add(self.panel_graph, 1, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_6, 0, wx.EXPAND, 0)

        sizer_6.Add((0, 0), 0, 0, 0)

        self.button_save_gif = wx.Button(self, wx.ID_ANY, "Save GIF...")
        sizer_6.Add(self.button_save_gif, 0, wx.ALL, 4)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 0, wx.EXPAND, 0)

        self.text_ctrl_status = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.text_ctrl_status.SetMinSize((-1, 80))
        sizer_5.Add(self.text_ctrl_status, 1, wx.EXPAND, 0)

        sizer_export = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_export, 0, wx.ALL | wx.EXPAND, 4)

        self.button_export_area = wx.Button(self, wx.ID_ANY, "Export Area...")
        sizer_export.Add(self.button_export_area, 0, wx.ALL, 4)

        self.button_export_line = wx.Button(self, wx.ID_ANY, "Export Line...")
        sizer_export.Add(self.button_export_line, 0, wx.ALL, 4)

        self.button_export_axis = wx.Button(self, wx.ID_ANY, "Export Axis...")
        sizer_export.Add(self.button_export_axis, 0, wx.ALL, 4)

        sizer_export.Add((0, 0), 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_CLOSE = wx.Button(self, wx.ID_CLOSE, "")
        sizer_2.AddButton(self.button_CLOSE)

        sizer_2.Realize()

        self.SetSizer(sizer_1)

        self.SetEscapeId(self.button_CLOSE.GetId())

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.OnBtnSaveGIF, self.button_save_gif)
        self.Bind(wx.EVT_BUTTON, self.OnBtnExportArea, self.button_export_area)
        self.Bind(wx.EVT_BUTTON, self.OnBtnExportLine, self.button_export_line)
        self.Bind(wx.EVT_BUTTON, self.OnBtnExportAxis, self.button_export_axis)
        # end wxGlade

    def OnBtnSaveGIF(self, event):  # wxGlade: ResultViewerUI.<event_handler>
        print("Event handler 'OnBtnSaveGIF' not implemented!")
        event.Skip()

    def OnBtnExportArea(self, event):  # wxGlade: ResultViewerUI.<event_handler>
        print("Event handler 'OnBtnExportArea' not implemented!")
        event.Skip()

    def OnBtnExportLine(self, event):  # wxGlade: ResultViewerUI.<event_handler>
        print("Event handler 'OnBtnExportLine' not implemented!")
        event.Skip()

    def OnBtnExportAxis(self, event):  # wxGlade: ResultViewerUI.<event_handler>
        print("Event handler 'OnBtnExportAxis' not implemented!")
        event.Skip()

# end of class ResultViewerUI
