# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Jul 24 09:58:59 2026
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrameUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrameUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1531, 1178))
        self.SetTitle("frame")

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "&New Project\tCtrl+N", "")
        self.Bind(wx.EVT_MENU, self.OnBtnResetAll, item)
        wxglade_tmp_menu.Append(wx.ID_OPEN, "&Load Project...\tCtrl+L", "")
        self.Bind(wx.EVT_MENU, self.OnMenuLoad, id=wx.ID_OPEN)
        wxglade_tmp_menu.Append(wx.ID_SAVE, "&Save\tCtrl+S", "")
        self.Bind(wx.EVT_MENU, self.OnMenuSave, id=wx.ID_SAVE)
        wxglade_tmp_menu.Append(wx.ID_SAVEAS, "Save Project &As...\tCtrl+Shift+S", "")
        self.Bind(wx.EVT_MENU, self.OnMenuSaveAs, id=wx.ID_SAVEAS)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "&Import Superfish File...", "")
        self.Bind(wx.EVT_MENU, self.OnMenuImportSuperfish, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export MSH file...\tCtrl+M", "")
        self.Bind(wx.EVT_MENU, self.OnMrExportMsh, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export gmesh geo file...\tCtrl+G", "")
        self.Bind(wx.EVT_MENU, self.OnMrExportGeo, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export Python Script...\tCtrl+P", "")
        self.Bind(wx.EVT_MENU, self.OnMrExportPythonScript, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export Superfish .af...\tCtrl+A", "")
        self.Bind(wx.EVT_MENU, self.OnBtnExportSuperfish, item)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "E&xit", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "&File")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        self.sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1_pane_3.SetBackgroundColour(wx.Colour(239, 252, 255))
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Multi-Region Editor")

        self.sizer_mr_main = wx.BoxSizer(wx.HORIZONTAL)

        self.sizer_mr_canvas = wx.BoxSizer(wx.VERTICAL)
        self.sizer_mr_main.Add(self.sizer_mr_canvas, 2, wx.EXPAND, 0)

        self.sizer_mr_controls = wx.BoxSizer(wx.VERTICAL)
        self.sizer_mr_main.Add(self.sizer_mr_controls, 0, wx.EXPAND, 0)

        self.mr_view_mode_radiobox = wx.RadioBox(self.notebook_1_pane_3, wx.ID_ANY, "View Mode", choices=["Simple", "Advanced"], majorDimension=2, style=wx.RA_SPECIFY_COLS)
        self.mr_view_mode_radiobox.SetSelection(0)
        self.sizer_mr_controls.Add(self.mr_view_mode_radiobox, 0, wx.ALL | wx.EXPAND, 3)

        sb_mr_area = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_3, wx.ID_ANY, "Draw Area"), wx.HORIZONTAL)
        self.sizer_mr_controls.Add(sb_mr_area, 0, wx.ALL | wx.EXPAND, 3)

        label_mr_unit = wx.StaticText(sb_mr_area.GetStaticBox(), wx.ID_ANY, "Unit:")
        sb_mr_area.Add(label_mr_unit, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.mr_unit_choice = wx.Choice(sb_mr_area.GetStaticBox(), wx.ID_ANY, choices=["m", "cm", "mm", "inch"])
        self.mr_unit_choice.SetSelection(2)
        sb_mr_area.Add(self.mr_unit_choice, 0, 0, 0)

        label_17 = wx.StaticText(sb_mr_area.GetStaticBox(), wx.ID_ANY, "Z:")
        sb_mr_area.Add(label_17, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_xmin_ctrl = wx.TextCtrl(sb_mr_area.GetStaticBox(), wx.ID_ANY, "0")
        self.mr_xmin_ctrl.SetMinSize((50, -1))
        sb_mr_area.Add(self.mr_xmin_ctrl, 0, 0, 0)

        label_18 = wx.StaticText(sb_mr_area.GetStaticBox(), wx.ID_ANY, "-")
        sb_mr_area.Add(label_18, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_xmax_ctrl = wx.TextCtrl(sb_mr_area.GetStaticBox(), wx.ID_ANY, "100")
        self.mr_xmax_ctrl.SetMinSize((50, -1))
        sb_mr_area.Add(self.mr_xmax_ctrl, 0, 0, 0)

        label_19 = wx.StaticText(sb_mr_area.GetStaticBox(), wx.ID_ANY, "R:")
        sb_mr_area.Add(label_19, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_ymin_ctrl = wx.TextCtrl(sb_mr_area.GetStaticBox(), wx.ID_ANY, "0")
        self.mr_ymin_ctrl.SetMinSize((50, -1))
        sb_mr_area.Add(self.mr_ymin_ctrl, 0, 0, 0)

        label_20 = wx.StaticText(sb_mr_area.GetStaticBox(), wx.ID_ANY, "-")
        sb_mr_area.Add(label_20, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_ymax_ctrl = wx.TextCtrl(sb_mr_area.GetStaticBox(), wx.ID_ANY, "100")
        self.mr_ymax_ctrl.SetMinSize((50, -1))
        sb_mr_area.Add(self.mr_ymax_ctrl, 0, 0, 0)

        self.mr_update_limits_button = wx.Button(sb_mr_area.GetStaticBox(), wx.ID_ANY, "Update")
        sb_mr_area.Add(self.mr_update_limits_button, 0, wx.LEFT, 5)

        self.panel_simple_mode = wx.Panel(self.notebook_1_pane_3, wx.ID_ANY)
        self.panel_simple_mode.SetBackgroundColour(wx.Colour(239, 255, 196))
        self.sizer_mr_controls.Add(self.panel_simple_mode, 1, wx.EXPAND, 0)

        sizer_32 = wx.BoxSizer(wx.VERTICAL)

        sizer_33 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_32.Add(sizer_33, 0, wx.ALL, 1)

        self.mr_simple_close_loop_button = wx.Button(self.panel_simple_mode, wx.ID_ANY, "Close Loop")
        sizer_33.Add(self.mr_simple_close_loop_button, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_33.Add((20, 20), 0, 0, 0)

        self.mr_modeSimple_radiobox = wx.RadioBox(self.panel_simple_mode, wx.ID_ANY, "Edit Mode", choices=["Edit Points", "Edit Lines"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.mr_modeSimple_radiobox.Enable(False)
        self.mr_modeSimple_radiobox.SetSelection(0)
        sizer_33.Add(self.mr_modeSimple_radiobox, 0, 0, 0)

        sizer_34 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_32.Add(sizer_34, 0, wx.EXPAND, 0)

        sizer_34.Add((20, 20), 1, wx.EXPAND, 0)

        self.mr_simple_reset_button = wx.Button(self.panel_simple_mode, wx.ID_ANY, "Reset All")
        self.mr_simple_reset_button.SetBackgroundColour(wx.Colour(255, 153, 95))
        sizer_34.Add(self.mr_simple_reset_button, 0, wx.ALL, 5)

        sb_mr_pt = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_3, wx.ID_ANY, "Selected Point"), wx.VERTICAL)
        self.sizer_mr_controls.Add(sb_mr_pt, 0, wx.ALL | wx.EXPAND, 3)

        self.mr_selected_point_label = wx.StaticText(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "Point: -")
        sb_mr_pt.Add(self.mr_selected_point_label, 0, 0, 0)

        row_mr_pt = wx.BoxSizer(wx.HORIZONTAL)
        sb_mr_pt.Add(row_mr_pt, 0, wx.EXPAND, 0)

        label_21 = wx.StaticText(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "Z:")
        row_mr_pt.Add(label_21, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_point_z_ctrl = wx.TextCtrl(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "")
        self.mr_point_z_ctrl.SetMinSize((110, -1))
        row_mr_pt.Add(self.mr_point_z_ctrl, 0, 0, 0)

        self.mr_point_z_value_label = wx.StaticText(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "")
        self.mr_point_z_value_label.SetMinSize((80, -1))
        self.mr_point_z_value_label.SetForegroundColour(wx.Colour(128, 128, 128))
        row_mr_pt.Add(self.mr_point_z_value_label, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        label_22 = wx.StaticText(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "R:")
        row_mr_pt.Add(label_22, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_point_r_ctrl = wx.TextCtrl(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "")
        self.mr_point_r_ctrl.SetMinSize((110, -1))
        row_mr_pt.Add(self.mr_point_r_ctrl, 0, 0, 0)

        self.mr_point_r_value_label = wx.StaticText(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "")
        self.mr_point_r_value_label.SetMinSize((80, -1))
        self.mr_point_r_value_label.SetForegroundColour(wx.Colour(128, 128, 128))
        row_mr_pt.Add(self.mr_point_r_value_label, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.mr_update_point_button = wx.Button(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "Update")
        row_mr_pt.Add(self.mr_update_point_button, 0, wx.LEFT, 3)

        self.mr_delete_point_button = wx.Button(sb_mr_pt.GetStaticBox(), wx.ID_ANY, "Delete")
        row_mr_pt.Add(self.mr_delete_point_button, 0, wx.LEFT, 3)

        sb_mr_seg = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_3, wx.ID_ANY, "Selected Segment"), wx.VERTICAL)
        self.sizer_mr_controls.Add(sb_mr_seg, 0, wx.ALL | wx.EXPAND, 3)

        self.mr_selected_segment_label = wx.StaticText(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "Segment: -")
        sb_mr_seg.Add(self.mr_selected_segment_label, 0, 0, 0)

        row_mr_seg = wx.BoxSizer(wx.HORIZONTAL)
        sb_mr_seg.Add(row_mr_seg, 0, wx.EXPAND, 0)

        label_23 = wx.StaticText(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "Boundary Condition : ")
        row_mr_seg.Add(label_23, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_bc_choice = wx.Choice(sb_mr_seg.GetStaticBox(), wx.ID_ANY, choices=["PEC", "E-short", "M-short", "None"])
        self.mr_bc_choice.SetSelection(0)
        row_mr_seg.Add(self.mr_bc_choice, 0, 0, 0)

        self.mr_delete_segment_button = wx.Button(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "Delete Segment")
        row_mr_seg.Add(self.mr_delete_segment_button, 0, wx.LEFT, 5)

        row_mr_arc1 = wx.BoxSizer(wx.HORIZONTAL)
        sb_mr_seg.Add(row_mr_arc1, 0, wx.EXPAND, 0)

        self.mr_convert_arc_button = wx.Button(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "Convert to Arc")
        row_mr_arc1.Add(self.mr_convert_arc_button, 0, wx.ALL, 3)

        self.mr_convert_line_button = wx.Button(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "Convert to Line")
        row_mr_arc1.Add(self.mr_convert_line_button, 0, wx.ALL, 3)

        row_mr_arc2 = wx.BoxSizer(wx.HORIZONTAL)
        sb_mr_seg.Add(row_mr_arc2, 0, wx.EXPAND, 0)

        label_arc_cz = wx.StaticText(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "Center Z:")
        row_mr_arc2.Add(label_arc_cz, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_arc_center_z_ctrl = wx.TextCtrl(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "")
        self.mr_arc_center_z_ctrl.SetMinSize((110, -1))
        row_mr_arc2.Add(self.mr_arc_center_z_ctrl, 0, 0, 0)

        self.mr_arc_center_z_value_label = wx.StaticText(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "")
        self.mr_arc_center_z_value_label.SetMinSize((80, -1))
        self.mr_arc_center_z_value_label.SetForegroundColour(wx.Colour(128, 128, 128))
        row_mr_arc2.Add(self.mr_arc_center_z_value_label, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        label_arc_cr = wx.StaticText(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "R:")
        row_mr_arc2.Add(label_arc_cr, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_arc_center_r_ctrl = wx.TextCtrl(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "")
        self.mr_arc_center_r_ctrl.SetMinSize((110, -1))
        row_mr_arc2.Add(self.mr_arc_center_r_ctrl, 0, 0, 0)

        self.mr_arc_center_r_value_label = wx.StaticText(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "")
        self.mr_arc_center_r_value_label.SetMinSize((80, -1))
        self.mr_arc_center_r_value_label.SetForegroundColour(wx.Colour(128, 128, 128))
        row_mr_arc2.Add(self.mr_arc_center_r_value_label, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.mr_update_center_button = wx.Button(sb_mr_seg.GetStaticBox(), wx.ID_ANY, "Update Center")
        row_mr_arc2.Add(self.mr_update_center_button, 0, wx.LEFT, 3)

        self.panel_advanced_mode = wx.Panel(self.notebook_1_pane_3, wx.ID_ANY)
        self.panel_advanced_mode.SetBackgroundColour(wx.Colour(255, 239, 159))
        self.panel_advanced_mode.Hide()
        self.sizer_mr_controls.Add(self.panel_advanced_mode, 1, wx.EXPAND, 0)

        sizer_31 = wx.BoxSizer(wx.VERTICAL)

        self.mr_mode_radiobox = wx.RadioBox(self.panel_advanced_mode, wx.ID_ANY, "Edit Mode", choices=["Add Points", "Edit Points", "Add Segments", "Build Loop", "Edit BC"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.mr_mode_radiobox.SetSelection(0)
        sizer_31.Add(self.mr_mode_radiobox, 0, wx.ALL | wx.EXPAND, 3)

        sb_mr_lp = wx.StaticBoxSizer(wx.StaticBox(self.panel_advanced_mode, wx.ID_ANY, "Loops"), wx.VERTICAL)
        sizer_31.Add(sb_mr_lp, 0, wx.ALL | wx.EXPAND, 3)

        self.mr_loop_list = wx.ListBox(sb_mr_lp.GetStaticBox(), wx.ID_ANY, choices=[], style=0)
        sb_mr_lp.Add(self.mr_loop_list, 1, wx.EXPAND, 0)

        row_mr_lp = wx.BoxSizer(wx.HORIZONTAL)
        sb_mr_lp.Add(row_mr_lp, 0, wx.EXPAND, 0)

        self.mr_close_loop_button = wx.Button(sb_mr_lp.GetStaticBox(), wx.ID_ANY, "Close Loop")
        row_mr_lp.Add(self.mr_close_loop_button, 0, wx.LEFT, 3)

        self.mr_cancel_loop_button = wx.Button(sb_mr_lp.GetStaticBox(), wx.ID_ANY, "Cancel")
        row_mr_lp.Add(self.mr_cancel_loop_button, 0, wx.LEFT, 3)

        self.mr_delete_loop_button = wx.Button(sb_mr_lp.GetStaticBox(), wx.ID_ANY, "Delete")
        row_mr_lp.Add(self.mr_delete_loop_button, 0, wx.LEFT, 3)

        sb_mr_rg = wx.StaticBoxSizer(wx.StaticBox(self.panel_advanced_mode, wx.ID_ANY, "Regions"), wx.VERTICAL)
        sizer_31.Add(sb_mr_rg, 1, wx.ALL | wx.EXPAND, 3)

        self.mr_region_list = wx.ListBox(sb_mr_rg.GetStaticBox(), wx.ID_ANY, choices=[])
        sb_mr_rg.Add(self.mr_region_list, 1, wx.EXPAND, 0)

        gs_rg = wx.BoxSizer(wx.VERTICAL)
        sb_mr_rg.Add(gs_rg, 0, wx.EXPAND, 0)

        sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
        gs_rg.Add(sizer_26, 0, wx.EXPAND, 0)

        label_25 = wx.StaticText(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Name: ")
        label_25.SetMinSize((80, 16))
        sizer_26.Add(label_25, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_region_name_ctrl = wx.TextCtrl(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Vacuum")
        sizer_26.Add(self.mr_region_name_ctrl, 1, wx.EXPAND, 0)

        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
        gs_rg.Add(sizer_27, 0, wx.EXPAND, 0)

        label_26 = wx.StaticText(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Outer Loop:  ")
        label_26.SetMinSize((80, 16))
        sizer_27.Add(label_26, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_region_outer_choice = wx.Choice(sb_mr_rg.GetStaticBox(), wx.ID_ANY, choices=[])
        sizer_27.Add(self.mr_region_outer_choice, 1, wx.EXPAND, 0)

        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        gs_rg.Add(sizer_28, 0, wx.EXPAND, 0)

        label_27 = wx.StaticText(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Hols:  ")
        label_27.SetMinSize((80, 16))
        sizer_28.Add(label_27, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_region_holes_list = wx.CheckListBox(sb_mr_rg.GetStaticBox(), wx.ID_ANY, choices=[])
        sizer_28.Add(self.mr_region_holes_list, 1, wx.EXPAND, 0)

        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)
        gs_rg.Add(sizer_29, 1, wx.EXPAND, 0)

        label_28 = wx.StaticText(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Material tag:")
        label_28.SetMinSize((80, 16))
        sizer_29.Add(label_28, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)

        self.mr_region_mat_ctrl = wx.TextCtrl(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "vacuum")
        sizer_29.Add(self.mr_region_mat_ctrl, 1, wx.EXPAND, 0)

        sizer_30 = wx.BoxSizer(wx.HORIZONTAL)
        gs_rg.Add(sizer_30, 1, wx.EXPAND, 0)

        label_29 = wx.StaticText(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "eps_r: ")
        label_29.SetMinSize((80, 16))
        sizer_30.Add(label_29, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_region_eps_ctrl = wx.TextCtrl(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "1.0")
        sizer_30.Add(self.mr_region_eps_ctrl, 1, wx.EXPAND, 0)

        sizer_30.Add((50, 20), 0, 0, 0)

        label_mr_tand = wx.StaticText(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "tan_d: ")
        label_mr_tand.SetMinSize((80, 16))
        sizer_30.Add(label_mr_tand, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.mr_region_tand_ctrl = wx.TextCtrl(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "0.0")
        sizer_30.Add(self.mr_region_tand_ctrl, 1, wx.EXPAND, 0)

        row_mr_rg = wx.BoxSizer(wx.HORIZONTAL)
        sb_mr_rg.Add(row_mr_rg, 0, wx.EXPAND, 0)

        self.mr_add_region_button = wx.Button(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Add")
        row_mr_rg.Add(self.mr_add_region_button, 0, 0, 0)

        self.mr_update_region_button = wx.Button(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Update")
        row_mr_rg.Add(self.mr_update_region_button, 0, wx.LEFT, 3)

        self.mr_delete_region_button = wx.Button(sb_mr_rg.GetStaticBox(), wx.ID_ANY, "Delete")
        row_mr_rg.Add(self.mr_delete_region_button, 0, wx.LEFT, 3)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_mr_controls.Add(sizer_2, 1, wx.EXPAND, 0)

        self.button_open_parametor = wx.Button(self.notebook_1_pane_3, wx.ID_ANY, "Open Parametor Window...")
        sizer_2.Add(self.button_open_parametor, 0, 0, 0)

        sizer_2.Add((0, 0), 0, 0, 0)

        self.panel_mr_variables = wx.Panel(self.notebook_1_pane_3, wx.ID_ANY)
        self.sizer_mr_controls.Add(self.panel_mr_variables, 2, wx.ALL | wx.EXPAND, 3)

        sb_mr_mesh = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_3, wx.ID_ANY, "Mesh Output"), wx.HORIZONTAL)
        self.sizer_mr_controls.Add(sb_mr_mesh, 0, wx.ALL | wx.EXPAND, 3)

        label_30 = wx.StaticText(sb_mr_mesh.GetStaticBox(), wx.ID_ANY, "lc:")
        sb_mr_mesh.Add(label_30, 0, wx.ALIGN_BOTTOM | wx.ALL, 3)

        self.mr_mesh_size_ctrl = wx.TextCtrl(sb_mr_mesh.GetStaticBox(), wx.ID_ANY, "5")
        self.mr_mesh_size_ctrl.SetMinSize((60, -1))
        sb_mr_mesh.Add(self.mr_mesh_size_ctrl, 0, wx.ALIGN_BOTTOM, 0)

        self.mr_mesh_order_radiobox = wx.RadioBox(sb_mr_mesh.GetStaticBox(), wx.ID_ANY, "Order", choices=["1st", "2nd"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.mr_mesh_order_radiobox.SetSelection(1)
        sb_mr_mesh.Add(self.mr_mesh_order_radiobox, 0, wx.LEFT, 5)

        self.mr_export_msh_button = wx.Button(sb_mr_mesh.GetStaticBox(), wx.ID_ANY, "Export MSH")
        sb_mr_mesh.Add(self.mr_export_msh_button, 0, wx.ALIGN_BOTTOM | wx.LEFT, 5)

        self.mr_export_geo_button = wx.Button(sb_mr_mesh.GetStaticBox(), wx.ID_ANY, "Export to .geo")
        sb_mr_mesh.Add(self.mr_export_geo_button, 0, wx.ALIGN_BOTTOM, 0)

        self.mr_export_py_button = wx.Button(sb_mr_mesh.GetStaticBox(), wx.ID_ANY, "Export Python Script")
        sb_mr_mesh.Add(self.mr_export_py_button, 0, wx.ALIGN_BOTTOM, 0)

        self.mr_hint_ctrl = wx.TextCtrl(self.notebook_1_pane_3, wx.ID_ANY, u"クリックで点を追加。Mode を切り替えて編集してください。", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.sizer_mr_controls.Add(self.mr_hint_ctrl, 0, wx.ALL | wx.EXPAND, 3)

        self.sizer_mr_controls.Add((0, 0), 0, 0, 0)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, "FEM Analysis")

        self.sizer_fem_main = wx.BoxSizer(wx.VERTICAL)

        sizer_fem_solver = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_2, wx.ID_ANY, "Solver Settings"), wx.VERTICAL)
        self.sizer_fem_main.Add(sizer_fem_solver, 0, wx.ALL | wx.EXPAND, 5)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_solver.Add(sizer_18, 0, wx.EXPAND, 0)

        label_mesh_file = wx.StaticText(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Mesh File:")
        sizer_18.Add(label_mesh_file, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.fem_mesh_path_ctrl = wx.TextCtrl(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "")
        sizer_18.Add(self.fem_mesh_path_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.btn_browse_mesh = wx.Button(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Browse...")
        sizer_18.Add(self.btn_browse_mesh, 0, wx.ALL, 5)

        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_solver.Add(sizer_23, 1, wx.EXPAND, 0)

        self.radio_box_analysis_mode = wx.RadioBox(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Analysis Mode", choices=["TM0", "HOM"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.radio_box_analysis_mode.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        self.radio_box_analysis_mode.SetSelection(0)
        sizer_23.Add(self.radio_box_analysis_mode, 0, wx.ALL, 5)

        label_hom_order = wx.StaticText(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Mode Orders (e.g. 0 1 2):")
        sizer_23.Add(label_hom_order, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.hom_order_ctrl = wx.TextCtrl(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "0 1")
        self.hom_order_ctrl.Enable(False)
        sizer_23.Add(self.hom_order_ctrl, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_23.Add((20, 20), 0, 0, 0)

        self.radio_mesh_order = wx.RadioBox(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Mesh Order", choices=["1st Order", "2nd Order"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.radio_mesh_order.SetSelection(1)
        sizer_23.Add(self.radio_mesh_order, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_23.Add((0, 0), 0, 0, 0)

        sizer_23.Add((0, 0), 0, 0, 0)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_solver.Add(sizer_9, 0, wx.EXPAND, 0)

        self.fem_wave_type_radio = wx.RadioBox(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Wave Type", choices=["Standing Wave", "Traveling Wave"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.fem_wave_type_radio.SetSelection(0)
        sizer_9.Add(self.fem_wave_type_radio, 0, wx.ALL, 5)

        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_24, 0, wx.EXPAND, 0)

        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24.Add(sizer_25, 0, wx.EXPAND, 0)

        label_phase = wx.StaticText(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Phase Shift (deg):")
        sizer_25.Add(label_phase, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.fem_phase_shift_ctrl = wx.TextCtrl(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "120.0")
        self.fem_phase_shift_ctrl.SetMinSize((150, 23))
        self.fem_phase_shift_ctrl.Enable(False)
        sizer_25.Add(self.fem_phase_shift_ctrl, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        label_16 = wx.StaticText(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "(e.g. \"120\", \"60,90,120\", \"0:180:20\")")
        sizer_24.Add(label_16, 0, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 5)

        sizer_9.Add((20, 20), 0, 0, 0)

        label_modes = wx.StaticText(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Number of Modes:")
        sizer_9.Add(label_modes, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.num_modes_ctrl = wx.SpinCtrl(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "10", min=1, max=100)
        sizer_9.Add(self.num_modes_ctrl, 0, wx.ALIGN_BOTTOM | wx.ALL, 3)

        sizer_9.Add((20, 20), 0, 0, 0)

        label_1 = wx.StaticText(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Predicted frequency:")
        sizer_9.Add(label_1, 0, wx.ALIGN_BOTTOM | wx.BOTTOM, 5)

        self.predicted_frequency_ctrl = wx.TextCtrl(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "")
        self.predicted_frequency_ctrl.SetMinSize((100, 23))
        sizer_9.Add(self.predicted_frequency_ctrl, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        label_2 = wx.StaticText(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "GHz")
        sizer_9.Add(label_2, 0, wx.ALIGN_BOTTOM | wx.BOTTOM, 5)

        sizer_9.Add((30, 20), 0, 0, 0)

        self.btn_run_solver = wx.Button(sizer_fem_solver.GetStaticBox(), wx.ID_ANY, "Run Solver")
        self.btn_run_solver.SetBackgroundColour(wx.Colour(175, 216, 255))
        self.btn_run_solver.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        sizer_9.Add(self.btn_run_solver, 0, wx.ALIGN_BOTTOM | wx.LEFT | wx.RIGHT, 5)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_9.Add((0, 0), 0, 0, 0)

        sizer_fem_post = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_2, wx.ID_ANY, "Post-Process Settings"), wx.VERTICAL)
        self.sizer_fem_main.Add(sizer_fem_post, 0, wx.ALL | wx.EXPAND, 5)

        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_20, 0, wx.EXPAND, 0)

        label_14 = wx.StaticText(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Raw Result File: ")
        sizer_20.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.fem_raw_result_path_ctrl = wx.TextCtrl(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "")
        sizer_20.Add(self.fem_raw_result_path_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.btn_browse_raw_result = wx.Button(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Browse...")
        sizer_20.Add(self.btn_browse_raw_result, 0, wx.ALL, 5)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_19, 0, wx.EXPAND, 0)

        label_cond = wx.StaticText(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Conductivity [S/m]:")
        sizer_19.Add(label_cond, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.fem_conductivity_ctrl = wx.TextCtrl(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "5.8e7")
        sizer_19.Add(self.fem_conductivity_ctrl, 0, wx.ALL, 5)

        label_beta = wx.StaticText(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Beta (v/c):")
        sizer_19.Add(label_beta, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        self.fem_beta_ctrl = wx.TextCtrl(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "1.0")
        sizer_19.Add(self.fem_beta_ctrl, 0, wx.ALL, 5)

        self.btn_run_post = wx.Button(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Run Post-Process")
        self.btn_run_post.SetBackgroundColour(wx.Colour(255, 211, 127))
        self.btn_run_post.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        sizer_19.Add(self.btn_run_post, 0, wx.ALL, 5)

        sizer_19.Add((0, 0), 0, 0, 0)

        sizer_19.Add((0, 0), 0, 0, 0)

        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_21, 1, wx.EXPAND, 0)

        label_15 = wx.StaticText(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Post-Processed Result File: ")
        sizer_21.Add(label_15, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.fem_processed_result_path_ctrl = wx.TextCtrl(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "")
        sizer_21.Add(self.fem_processed_result_path_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.btn_browse_processed_result = wx.Button(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Browse...")
        sizer_21.Add(self.btn_browse_processed_result, 0, wx.ALL, 5)

        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_fem_post.Add(sizer_22, 0, wx.EXPAND, 0)

        self.btn_view_results = wx.Button(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Result Viewer")
        self.btn_view_results.SetBackgroundColour(wx.Colour(184, 254, 220))
        self.btn_view_results.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        sizer_22.Add(self.btn_view_results, 0, wx.ALL, 5)

        sizer_22.Add((50, 20), 0, 0, 0)

        self.btn_create_report = wx.Button(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Create HTML Report")
        sizer_22.Add(self.btn_create_report, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        self.checkbox_report_anim = wx.CheckBox(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Create animation")
        sizer_22.Add(self.checkbox_report_anim, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_22.Add((20, 20), 0, 0, 0)

        self.btn_open_report = wx.Button(sizer_fem_post.GetStaticBox(), wx.ID_ANY, "Open HTML Report")
        sizer_22.Add(self.btn_open_report, 0, wx.ALIGN_BOTTOM | wx.ALL, 5)

        sizer_22.Add((0, 0), 0, 0, 0)

        self.fem_log_ctrl = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.fem_log_ctrl.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.fem_log_ctrl.SetForegroundColour(wx.Colour(255, 255, 255))
        self.fem_log_ctrl.SetFont(wx.Font(10, wx.FONTFAMILY_MODERN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Consolas"))
        self.sizer_fem_main.Add(self.fem_log_ctrl, 1, wx.ALL | wx.EXPAND, 5)

        self.notebook_1_pane_2.SetSizer(self.sizer_fem_main)

        self.panel_advanced_mode.SetSizer(sizer_31)

        self.panel_simple_mode.SetSizer(sizer_32)

        self.notebook_1_pane_3.SetSizer(self.sizer_mr_main)

        self.panel_1.SetSizer(self.sizer_1)

        self.Layout()

        self.mr_view_mode_radiobox.Bind(wx.EVT_RADIOBOX, self.OnMrViewModeChange)
        self.mr_unit_choice.Bind(wx.EVT_CHOICE, self.OnMrUnitChange)
        self.mr_update_limits_button.Bind(wx.EVT_BUTTON, self.OnMrUpdateLimits)
        self.mr_simple_close_loop_button.Bind(wx.EVT_BUTTON, self.OnBtnMrCloseLoop)
        self.mr_modeSimple_radiobox.Bind(wx.EVT_RADIOBOX, self.on_mode_change)
        self.mr_simple_reset_button.Bind(wx.EVT_BUTTON, self.OnBtnResetAll)
        self.mr_update_point_button.Bind(wx.EVT_BUTTON, self.OnMrUpdatePoint)
        self.mr_delete_point_button.Bind(wx.EVT_BUTTON, self.OnMrDeletePoint)
        self.mr_bc_choice.Bind(wx.EVT_CHOICE, self.OnMrBcChoice)
        self.mr_delete_segment_button.Bind(wx.EVT_BUTTON, self.OnMrDeleteSegment)
        self.mr_convert_arc_button.Bind(wx.EVT_BUTTON, self.OnMrConvertToArc)
        self.mr_convert_line_button.Bind(wx.EVT_BUTTON, self.OnMrConvertToLine)
        self.mr_update_center_button.Bind(wx.EVT_BUTTON, self.OnMrUpdateCenter)
        self.mr_mode_radiobox.Bind(wx.EVT_RADIOBOX, self.OnMrModeChange)
        self.mr_loop_list.Bind(wx.EVT_LISTBOX, self.OnMrLoopSelected)
        self.mr_close_loop_button.Bind(wx.EVT_BUTTON, self.OnMrCloseLoop)
        self.mr_cancel_loop_button.Bind(wx.EVT_BUTTON, self.OnMrCancelLoop)
        self.mr_delete_loop_button.Bind(wx.EVT_BUTTON, self.OnMrDeleteLoop)
        self.mr_region_list.Bind(wx.EVT_LISTBOX, self.OnMrRegionSelected)
        self.mr_add_region_button.Bind(wx.EVT_BUTTON, self.OnMrAddRegion)
        self.mr_update_region_button.Bind(wx.EVT_BUTTON, self.OnMrUpdateRegion)
        self.mr_delete_region_button.Bind(wx.EVT_BUTTON, self.OnMrDeleteRegion)
        self.button_open_parametor.Bind(wx.EVT_BUTTON, self.OnBtnOpenParametor)
        self.mr_export_msh_button.Bind(wx.EVT_BUTTON, self.OnMrExportMsh)
        self.mr_export_geo_button.Bind(wx.EVT_BUTTON, self.OnMrExportGeo)
        self.mr_export_py_button.Bind(wx.EVT_BUTTON, self.OnMrExportPythonScript)
        self.btn_browse_mesh.Bind(wx.EVT_BUTTON, self.OnBrowseMesh)
        self.radio_box_analysis_mode.Bind(wx.EVT_RADIOBOX, self.on_radio_box_analysis_mode)
        self.fem_wave_type_radio.Bind(wx.EVT_RADIOBOX, self.on_fem_wave_type_radio)
        self.btn_run_solver.Bind(wx.EVT_BUTTON, self.OnRunSolver)
        self.btn_browse_raw_result.Bind(wx.EVT_BUTTON, self.OnBrowseRawResult)
        self.btn_run_post.Bind(wx.EVT_BUTTON, self.OnRunPost)
        self.btn_browse_processed_result.Bind(wx.EVT_BUTTON, self.OnBrowseProcessedResult)
        self.btn_view_results.Bind(wx.EVT_BUTTON, self.OnViewResults)
        self.btn_create_report.Bind(wx.EVT_BUTTON, self.OnBtnCreateReport)
        self.btn_open_report.Bind(wx.EVT_BUTTON, self.OnOpenReport)
        # end wxGlade

    def OnBtnResetAll(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnResetAll' not implemented!")
        event.Skip()

    def OnMenuLoad(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuLoad' not implemented!")
        event.Skip()

    def OnMenuSave(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuSave' not implemented!")
        event.Skip()

    def OnMenuSaveAs(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuSaveAs' not implemented!")
        event.Skip()

    def OnMenuImportSuperfish(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMenuImportSuperfish' not implemented!")
        event.Skip()

    def OnMrExportMsh(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrExportMsh' not implemented!")
        event.Skip()

    def OnMrExportGeo(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrExportGeo' not implemented!")
        event.Skip()

    def OnMrExportPythonScript(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrExportPythonScript' not implemented!")
        event.Skip()

    def OnBtnExportSuperfish(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnExportSuperfish' not implemented!")
        event.Skip()

    def OnMrViewModeChange(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrViewModeChange' not implemented!")
        event.Skip()

    def OnMrUnitChange(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrUnitChange' not implemented!")
        event.Skip()

    def OnMrUpdateLimits(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrUpdateLimits' not implemented!")
        event.Skip()

    def OnBtnMrCloseLoop(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnMrCloseLoop' not implemented!")
        event.Skip()

    def on_mode_change(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_mode_change' not implemented!")
        event.Skip()

    def OnMrUpdatePoint(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrUpdatePoint' not implemented!")
        event.Skip()

    def OnMrDeletePoint(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrDeletePoint' not implemented!")
        event.Skip()

    def OnMrBcChoice(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrBcChoice' not implemented!")
        event.Skip()

    def OnMrDeleteSegment(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrDeleteSegment' not implemented!")
        event.Skip()

    def OnMrConvertToArc(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrConvertToArc' not implemented!")
        event.Skip()

    def OnMrConvertToLine(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrConvertToLine' not implemented!")
        event.Skip()

    def OnMrUpdateCenter(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrUpdateCenter' not implemented!")
        event.Skip()

    def OnMrModeChange(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrModeChange' not implemented!")
        event.Skip()

    def OnMrLoopSelected(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrLoopSelected' not implemented!")
        event.Skip()

    def OnMrCloseLoop(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrCloseLoop' not implemented!")
        event.Skip()

    def OnMrCancelLoop(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrCancelLoop' not implemented!")
        event.Skip()

    def OnMrDeleteLoop(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrDeleteLoop' not implemented!")
        event.Skip()

    def OnMrRegionSelected(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrRegionSelected' not implemented!")
        event.Skip()

    def OnMrAddRegion(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrAddRegion' not implemented!")
        event.Skip()

    def OnMrUpdateRegion(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrUpdateRegion' not implemented!")
        event.Skip()

    def OnMrDeleteRegion(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnMrDeleteRegion' not implemented!")
        event.Skip()

    def OnBtnOpenParametor(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnOpenParametor' not implemented!")
        event.Skip()

    def OnBrowseMesh(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBrowseMesh' not implemented!")
        event.Skip()

    def on_radio_box_analysis_mode(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_radio_box_analysis_mode' not implemented!")
        event.Skip()

    def on_fem_wave_type_radio(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'on_fem_wave_type_radio' not implemented!")
        event.Skip()

    def OnRunSolver(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnRunSolver' not implemented!")
        event.Skip()

    def OnBrowseRawResult(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBrowseRawResult' not implemented!")
        event.Skip()

    def OnRunPost(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnRunPost' not implemented!")
        event.Skip()

    def OnBrowseProcessedResult(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBrowseProcessedResult' not implemented!")
        event.Skip()

    def OnViewResults(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnViewResults' not implemented!")
        event.Skip()

    def OnBtnCreateReport(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnBtnCreateReport' not implemented!")
        event.Skip()

    def OnOpenReport(self, event):  # wxGlade: MyFrameUI.<event_handler>
        print("Event handler 'OnOpenReport' not implemented!")
        event.Skip()

# end of class MyFrameUI
