"""リボンのアイコン（`src/axicavity_fem/gui/ui/icons/*.svg`、24×24 の線画）を書き出す.

EM-CAD-py `tools/make_icons.py` からの転用（部品と色を共有し、ver3 で使うものと ver3 固有のアイコンを足した）。
アイコンは手で SVG を直さず、ここを直して実行し直す（色と線の太さをそろえるため）:

    python tools/make_icons.py                 # gui/ui/icons/ に書き出す（ACTION_ICONS に現れる名前だけ）
    python tools/make_icons.py --sheet a.png   # 確認用の一覧画像（18 / 24 / 48 px、要 PySide6）

色: 線 INK、強調 ACC（淡い塗り ACC_FILL）、隠れ線・補助 MUTED。境界条件は 2D 画面と同じ ver2.3 の色
（PEC 橙・E-short 青・M-short 緑・None 灰）、構築線はスケッチ画面と同じ紫。操作とアイコンの対応は
`axicavity_fem/gui/ui/icon_set.py` の ACTION_ICONS。
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ICON_DIR = ROOT / "src" / "axicavity_fem" / "gui" / "ui" / "icons"

INK, ACC, ACC_FILL, MUTED = "#334155", "#2563eb", "#dbeafe", "#94a3b8"
GREEN, RED, ORANGE = "#16a34a", "#dc2626", "#f97316"
BC = {"pec": "#cc6600", "eshort": "#1f77b4", "mshort": "#2ca02c", "none": "#444444"}   # ver2.3 の色
CONSTRUCTION = "#7c3aed"
HEAD = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="{ink}" '
        'stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'
        '<!-- generated by tools/make_icons.py -->')

DOC = '<path d="M3.5 3h7.5l3 3v14a1 1 0 0 1-1 1H3.5a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M11 3v3h3"/>'
OUT_ARROW = f'<path d="M16.5 12H22.5M20 9.5l2.5 2.5L20 14.5" stroke="{ACC}" stroke-width="1.9"/>'
IN_ARROW = f'<path d="M1.8 12H7.5M5 9.5L7.5 12 5 14.5" stroke="{ACC}" stroke-width="1.9"/>'
END_POINT = 'r="2" fill="#ffffff" stroke-width="1.4"'
AXIS_DASH = f'<path d="M2 20.5h20" stroke="{INK}" stroke-width="1.3" stroke-dasharray="4 1.6 1 1.6"/>'


def _hex_mesh(cx: float = 12.0, cy: float = 12.0, r: float = 9.0) -> str:
    """正六角形を正三角形 24 個に分けたメッシュ."""
    v = [(cx + r * math.cos(math.radians(60 * k)), cy + r * math.sin(math.radians(60 * k))) for k in range(6)]
    m = [((v[k][0] + v[(k + 1) % 6][0]) / 2, (v[k][1] + v[(k + 1) % 6][1]) / 2) for k in range(6)]

    def seg(a, b):
        return f"M{a[0]:.2f} {a[1]:.2f}L{b[0]:.2f} {b[1]:.2f}"
    inner = [seg(v[k], v[k + 3]) for k in range(3)]
    inner += [seg(m[(k + 3) % 6], m[(k + 5) % 6]) + seg(m[(k + 2) % 6], m[k]) for k in range(3)]
    outline = "M" + "L".join(f"{x:.2f} {y:.2f}" for x, y in v) + "z"
    return (f'<path d="{outline}" fill="{ACC_FILL}" stroke="none"/>'
            f'<path d="{"".join(inner)}" stroke="{ACC}" stroke-width="1.1"/>'
            f'<path d="{outline}" stroke-width="1.6"/>')


def _history_arrow(color: str, cx: float, cy: float, r: float) -> str:
    return (f'<path d="M{cx - 0.906 * r:.2f} {cy - 0.423 * r:.2f}A{r} {r} 0 1 1 '
            f'{cx - 0.819 * r:.2f} {cy + 0.574 * r:.2f}" stroke="{color}"/>'
            f'<path d="M{cx - 0.906 * r - 0.8:.2f} {cy - 0.423 * r - 2.9:.2f}L{cx - 0.906 * r:.2f} '
            f'{cy - 0.423 * r:.2f}l2.75-1.25" stroke="{color}"/>')


def _bc_line(color: str, dashed: bool = False) -> str:
    """境界条件（2D の曲線の色）: 空洞の輪郭で 1 辺だけ色付き."""
    dash = ' stroke-dasharray="2.4 2"' if dashed else ""
    return (f'<path d="M4 19.5V6.5h9.5a6.5 6.5 0 0 1 6.5 6.5v6.5" stroke="{MUTED}" stroke-width="1.4"/>'
            f'<path d="M4 6.5h9.5" stroke="{color}" stroke-width="2.6"{dash}/>'
            f'<path d="M4 19.5h16" stroke="{INK}" stroke-width="1.2" stroke-dasharray="4 1.6 1 1.6"/>')


JET_STOPS = ((0.0, "#1d4ed8"), (0.25, "#06b6d4"), (0.5, "#22c55e"), (0.75, "#facc15"), (1.0, "#dc2626"))


def _jet(t: float) -> str:
    t = min(1.0, max(0.0, t))
    for (t0, c0), (t1, c1) in zip(JET_STOPS, JET_STOPS[1:]):
        if t <= t1:
            f = (t - t0) / (t1 - t0)
            a = [int(c0[i:i + 2], 16) for i in (1, 3, 5)]
            b = [int(c1[i:i + 2], 16) for i in (1, 3, 5)]
            return "#" + "".join(f"{round(x + (y - x) * f):02x}" for x, y in zip(a, b))
    return JET_STOPS[-1][1]


def _gradient_cells(x0: float, y0: float, width: float, height: float, cols: int, rows: int) -> str:
    w, h = width / cols, height / rows
    return "".join(
        f'<rect x="{x0 + c * w:g}" y="{y0 + r * h:g}" width="{w:g}" height="{h:g}" '
        f'fill="{_jet((c + rows - 1 - r) / (cols + rows - 2))}" stroke="none"/>'
        for r in range(rows) for c in range(cols))


ICONS: dict[str, str] = {
    # --- ファイル ---
    "new": f'''<path d="M6 2.8h8.2L19 7.6v13.6H6z"/><path d="M14 2.8V7.6h5"/>
<path d="M12.5 11v7M9 14.5h7" stroke="{ACC}" stroke-width="1.8"/>''',
    "open": f'''<path d="M3 19V5.2a.9.9 0 0 1 .9-.9h5.3l2 2.2h7.5a.9.9 0 0 1 .9.9V10"/>
<path d="M3 19l2.7-7.9a.9.9 0 0 1 .85-.6H21.3a.6.6 0 0 1 .57.8L19.2 18.4a.9.9 0 0 1-.85.6H3z" stroke="{ACC}" fill="{ACC_FILL}"/>''',
    "recent": _history_arrow(INK, 12.5, 12.5, 8.5) + f'<path d="M12.5 8v4.5l3 2" stroke="{ACC}" stroke-width="1.8"/>',
    "save": f'''<path d="M5 3.5h11.5L20 7v12.5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-15a1 1 0 0 1 1-1z"/>
<path d="M7.5 3.5V8h7.5V3.5"/><rect x="7" y="12.5" width="10" height="6" rx=".6" stroke="{ACC}" fill="{ACC_FILL}"/>''',
    "save_as": f'''<path d="M4 3h9.5L17 6.5V16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/>
<path d="M6.2 3v3.8h6.3V3"/><rect x="5.8" y="10.5" width="8.4" height="4.5" rx=".5" stroke="{ACC}" fill="{ACC_FILL}"/>
<path d="M12.5 21l3.2-.8 6.5-6.5-2.4-2.4-6.5 6.5z" fill="#ffffff" stroke="{ACC}" stroke-width="1.5"/>
<path d="M18.4 13.1l2.4 2.4" stroke="{ACC}" stroke-width="1.3"/>''',
    "undo": '<path d="M9 13.5L4.5 9 9 4.5"/><path d="M4.5 9h10a5.5 5.5 0 0 1 0 11H10"/>',
    "redo": '<path d="M15 13.5L19.5 9 15 4.5"/><path d="M19.5 9h-10a5.5 5.5 0 0 0 0 11H14"/>',
    "import": f'''<path d="M10 4.5h10v15H10z" stroke="{ACC}" fill="{ACC_FILL}"/>
<path d="M10 9.5h10M10 14.5h10M15 4.5v15" stroke="{ACC}" stroke-width="1.1"/>''' + IN_ARROW,
    "import_superfish": f'''<path d="M9.5 4.5h11l-2 4 2 4-2 4 2 4h-11z" stroke="{ACC}" fill="{ACC_FILL}"/>
<path d="M12 8.5h5M12 12h5M12 15.5h5" stroke="{ACC}" stroke-width="1.1"/>''' + IN_ARROW,
    "export_model": DOC + f'''<path d="M6.8 9.5c-1.1 0-1.5.6-1.5 1.6v.8c0 .8-.4 1.3-1 1.3.6 0 1 .5 1 1.3v.8c0 1 .4 1.6 1.5 1.6
M9.2 9.5c1.1 0 1.5.6 1.5 1.6v.8c0 .8.4 1.3 1 1.3-.6 0-1 .5-1 1.3v.8c0 1-.4 1.6-1.5 1.6" stroke="{ACC}" stroke-width="1.3"/>''' + OUT_ARROW,
    "export_superfish": f'''<path d="M2.5 4.5h11l-2 4 2 4-2 4 2 4h-11z" stroke="{ACC}" fill="{ACC_FILL}"/>
<path d="M5 8.5h5M5 12h5M5 15.5h5" stroke="{ACC}" stroke-width="1.1"/>''' + OUT_ARROW,
    "export_msh": _hex_mesh(8.5, 12, 7.5) + OUT_ARROW,
    "export_geo": DOC + f'''<path d="M4.5 10.5h2.5a2 2 0 0 1 0 4h-1.5v-2h1.5" stroke="{ACC}" stroke-width="1.3"/>
<path d="M9 15.5v-5M11.5 15.5v-5" stroke="{ACC}" stroke-width="1.3"/>''' + OUT_ARROW,
    "export_python": DOC + f'''<path d="M6.5 10l-2 3 2 3M9.5 10l2 3-2 3" stroke="{ACC}" stroke-width="1.5"/>''' + OUT_ARROW,
    "units": f'''<path d="M3 15.5l12.5-12.5 6 6L9 21.5z" fill="{ACC_FILL}" stroke="{ACC}"/>
<path d="M6.5 12l2 2M9 9.5l2 2M11.5 7l2 2M14 4.5l2 2" stroke="{INK}" stroke-width="1.4"/>''',
    "language": f'''<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="3.8" ry="9" stroke="{ACC}" stroke-width="1.3"/>
<path d="M3 12h18M4.3 7.5h15.4M4.3 16.5h15.4" stroke="{ACC}" stroke-width="1.3"/>''',
    "about": f'''<circle cx="12" cy="12" r="9"/><path d="M12 10.8v6" stroke="{ACC}" stroke-width="2.2"/>
<circle cx="12" cy="7.4" r="1.3" fill="{ACC}" stroke="none"/>''',
    "quit": f'''<path d="M9.5 4H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h4.5"/>
<path d="M13 12h8.5M18 8.5l3.5 3.5-3.5 3.5" stroke="{RED}" stroke-width="1.9"/>''',
    # --- 作図 ---
    "select": '<path d="M6.5 3.5v15.2l4-3.8 2.9 6.2 2.8-1.3-2.9-6.1 5.5-.3z" fill="#ffffff" stroke-width="1.5"/>',
    "line": f'''<path d="M5.5 18.5l13-13" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="5.5" cy="18.5" r="2.1" fill="#ffffff"/><circle cx="18.5" cy="5.5" r="2.1" fill="#ffffff"/>''',
    "rectangle": f'''<rect x="4" y="6" width="16" height="12" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="4" cy="6" r="2" fill="#ffffff"/><circle cx="20" cy="18" r="2" fill="#ffffff"/>''',
    "circle": f'''<circle cx="12" cy="12" r="8" stroke="{ACC}" stroke-width="1.9"/>
<path d="M12 12l5.7-5.7" stroke-dasharray="1.6 1.8"/><circle cx="12" cy="12" r="1.7" fill="{INK}" stroke="none"/>''',
    "arc": f'''<path d="M4.5 16.5a7.5 7.5 0 0 1 15 0" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="4.5" cy="16.5" {END_POINT}/><circle cx="19.5" cy="16.5" {END_POINT}/>
<circle cx="12" cy="16.5" r="1.5" fill="{INK}" stroke="none"/>''',
    "polygon": f'''<path d="M12 3.5l7.36 4.25v8.5L12 20.5l-7.36-4.25v-8.5z" stroke="{ACC}" stroke-width="1.9"/>
<path d="M12 12l7.36-4.25" stroke-dasharray="1.6 1.8"/><circle cx="12" cy="12" r="1.5" fill="{INK}" stroke="none"/>''',
    "point": f'''<path d="M12 3.5v4.5M12 16v4.5M3.5 12H8M16 12h4.5" stroke-width="1.5"/>
<circle cx="12" cy="12" r="3" fill="{ACC}" stroke="none"/>''',
    "fillet": f'''<path d="M12 4h8v8" stroke="{MUTED}" stroke-dasharray="1.5 2"/>
<path d="M12 4H4v16h16v-8"/><path d="M12 4a8 8 0 0 1 8 8" stroke="{ACC}" stroke-width="2.1"/>''',
    "construction": f'''<path d="M5 19L19 5" stroke="{CONSTRUCTION}" stroke-width="1.9" stroke-dasharray="2.6 2.4"/>
<circle cx="5" cy="19" {END_POINT}/><circle cx="19" cy="5" {END_POINT}/>''',
    "insert_point": f'''<path d="M3.5 17.5l17-11" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="3.5" cy="17.5" {END_POINT}/><circle cx="20.5" cy="6.5" {END_POINT}/>
<circle cx="12" cy="12" r="2.6" fill="{ACC}" stroke="none"/><path d="M12 4v4M10 6h4" stroke="{INK}" stroke-width="1.5"/>''',
    "delete_reconnect": f'''<path d="M3.5 17.5l8.5-11 8.5 11" stroke="{MUTED}" stroke-width="1.4" stroke-dasharray="2 1.8"/>
<path d="M3.5 17.5h17" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="3.5" cy="17.5" {END_POINT}/><circle cx="20.5" cy="17.5" {END_POINT}/>
<path d="M9.5 4.5l5 5M14.5 4.5l-5 5" stroke="{RED}" stroke-width="1.9"/>''',
    "line_to_arc": f'''<path d="M4.5 16.5h15" stroke="{MUTED}" stroke-width="1.4" stroke-dasharray="2 1.8"/>
<path d="M4.5 16.5a7.5 7.5 0 0 1 15 0" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="4.5" cy="16.5" {END_POINT}/><circle cx="19.5" cy="16.5" {END_POINT}/>
<path d="M12 12.5v-4M10 10.5l2-2 2 2" stroke="{INK}" stroke-width="1.4"/>''',
    "arc_to_line": f'''<path d="M4.5 16.5a7.5 7.5 0 0 1 15 0" stroke="{MUTED}" stroke-width="1.4" stroke-dasharray="2 1.8"/>
<path d="M4.5 16.5h15" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="4.5" cy="16.5" {END_POINT}/><circle cx="19.5" cy="16.5" {END_POINT}/>
<path d="M12 8.5v4M10 10.5l2 2 2-2" stroke="{INK}" stroke-width="1.4"/>''',
    "close_polyline": f'''<path d="M4.5 19.5V8l7.5-3.5 7.5 3.5v11.5" stroke="{ACC}" stroke-width="1.9"/>
<path d="M4.5 19.5h15" stroke="{ACC}" stroke-width="1.9" stroke-dasharray="2.4 2"/>
<circle cx="4.5" cy="19.5" {END_POINT}/><circle cx="19.5" cy="19.5" {END_POINT}/>''',
    "split_intersections": f'''<path d="M4 20L20 4M4 4l16 16" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="4" cy="4" {END_POINT}/><circle cx="20" cy="4" {END_POINT}/><circle cx="4" cy="20" {END_POINT}/><circle cx="20" cy="20" {END_POINT}/>
<circle cx="12" cy="12" r="2.8" fill="{RED}" stroke="none"/>''',
    "fix_z0": f'''<path d="M3.5 2v20" stroke="{INK}" stroke-width="1.6"/>
<path d="M2 20.5h20" stroke="{INK}" stroke-width="1.1" stroke-dasharray="4 1.6 1 1.6"/>
<path d="M7 12h11" stroke="{MUTED}" stroke-width="1.3" stroke-dasharray="2 1.8"/>
<circle cx="3.5" cy="12" r="2.8" fill="{ACC}" stroke="none"/><circle cx="18" cy="12" r="2" fill="#ffffff" stroke-width="1.4"/>''',
    "fix_axis": AXIS_DASH + f'''<path d="M12 6v11" stroke="{MUTED}" stroke-width="1.3" stroke-dasharray="2 1.8"/>
<circle cx="12" cy="20.5" r="2.8" fill="{ACC}" stroke="none"/><circle cx="12" cy="6" r="2" fill="#ffffff" stroke-width="1.4"/>''',
    "fit": f'''<path d="M3 8.5V3h5.5M15.5 3H21v5.5M21 15.5V21h-5.5M8.5 21H3v-5.5" stroke-width="1.8"/>
<path d="M7.5 15.5V8.5h6.5a3.5 3.5 0 0 1 0 7z" stroke="{ACC}" stroke-width="1.5" fill="{ACC_FILL}"/>''',
    # --- 拘束・寸法 ---
    "coincident": f'''<path d="M3.5 19.5L12 12M20.5 19.5L12 12M12 12V3.5"/>
<circle cx="12" cy="12" r="2.8" fill="{ACC}" stroke="none"/>''',
    "horizontal": f'''<path d="M3.5 17h17" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="3.5" cy="17" r="1.8" fill="#ffffff"/><circle cx="20.5" cy="17" r="1.8" fill="#ffffff"/>
<path d="M9 4v7.5M15 4v7.5M9 7.75h6"/>''',
    "vertical": f'''<path d="M16.5 3.5v17" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="16.5" cy="3.5" r="1.8" fill="#ffffff"/><circle cx="16.5" cy="20.5" r="1.8" fill="#ffffff"/>
<path d="M4.5 8.5l3 7 3-7"/>''',
    "parallel": f'''<path d="M3.5 14.5L14.5 3.5" stroke-width="1.9"/><path d="M9.5 20.5l11-11" stroke="{ACC}" stroke-width="1.9"/>''',
    "perpendicular": f'''<path d="M3.5 19.5h17" stroke-width="1.9"/><path d="M9 19.5V3.5" stroke="{ACC}" stroke-width="1.9"/>
<path d="M9 15h4.5v4.5" stroke-width="1.2"/>''',
    "tangent": f'''<circle cx="11" cy="14" r="6.5"/><path d="M2.5 7.5h19" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="11" cy="7.5" r="1.9" fill="{ACC}" stroke="none"/>''',
    "equal": f'''<path d="M3.5 8.5l6-5M14.5 20.5l6-5" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="3.5" cy="8.5" r="1.6" fill="#ffffff" stroke-width="1.3"/><circle cx="9.5" cy="3.5" r="1.6" fill="#ffffff" stroke-width="1.3"/>
<circle cx="14.5" cy="20.5" r="1.6" fill="#ffffff" stroke-width="1.3"/><circle cx="20.5" cy="15.5" r="1.6" fill="#ffffff" stroke-width="1.3"/>
<path d="M8.5 10.3h7M8.5 13.7h7" stroke-width="2"/>''',
    "concentric": f'''<circle cx="12" cy="12" r="8.5"/><circle cx="12" cy="12" r="4.5" stroke="{ACC}" stroke-width="1.9"/>
<circle cx="12" cy="12" r="1.4" fill="{INK}" stroke="none"/>''',
    "fix": f'''<path d="M8 10.5V8a4 4 0 0 1 8 0v2.5" stroke-width="1.8"/>
<rect x="5.5" y="10.5" width="13" height="10" rx="1.5" fill="{ACC_FILL}" stroke="{ACC}"/>
<circle cx="12" cy="14.6" r="1.3" fill="{ACC}" stroke="none"/><path d="M12 15.5v2" stroke="{ACC}" stroke-width="1.4"/>''',
    "symmetric": f'''<path d="M12 3v18" stroke-width="1.3" stroke-dasharray="2 1.8"/>
<circle cx="4.8" cy="12" r="2.3" fill="{ACC}" stroke="none"/><circle cx="19.2" cy="12" r="2.3" fill="{ACC}" stroke="none"/>
<path d="M8 9.5l2.3 2.5L8 14.5M16 9.5L13.7 12l2.3 2.5" stroke-width="1.4"/>''',
    "point_on_curve": f'''<path d="M3 17c2.5-8.5 7.5-9.5 10-4.5s5.5 5 8-3.5" stroke-width="1.8"/>
<circle cx="13" cy="12.5" r="2.5" fill="{ACC}" stroke="none"/>''',
    "dimension": f'''<path d="M4 6v12M20 6v12" stroke="{MUTED}"/><path d="M4 12h16" stroke="{ACC}"/>
<path d="M7 9.5L4 12l3 2.5M17 9.5l3 2.5-3 2.5" stroke="{ACC}"/>''',
    "params": f'''<path d="M4 6.5h16M4 12h16M4 17.5h16" stroke-width="1.5"/>
<circle cx="14.5" cy="6.5" r="2.2" fill="#ffffff" stroke="{ACC}" stroke-width="1.8"/>
<circle cx="8.5" cy="12" r="2.2" fill="#ffffff" stroke="{ACC}" stroke-width="1.8"/>
<circle cx="16" cy="17.5" r="2.2" fill="#ffffff" stroke="{ACC}" stroke-width="1.8"/>''',
    # --- 物理 ---
    "bc_pec": _bc_line(BC["pec"]),
    "bc_eshort": _bc_line(BC["eshort"]),
    "bc_mshort": _bc_line(BC["mshort"]),
    "bc_none": _bc_line(BC["none"], dashed=True),
    "bc_auto": _bc_line(MUTED) + f'<path d="M14.5 4.5a4 4 0 1 1-3.5 6M11 7.5v3h3" stroke="{ACC}" stroke-width="1.5"/>',
    "region": f'''<path d="M4 19.5V6.5h9.5a6.5 6.5 0 0 1 6.5 6.5v6.5z" fill="{ACC_FILL}" stroke="{ACC}"/>
<path d="M7 12.5h7M7 15.5h5" stroke="{ACC}" stroke-width="1.2"/>''',
    "validate": f'''<circle cx="12" cy="12" r="8.5"/><path d="M7.5 12.5l3 3 6-6.5" stroke="{GREEN}" stroke-width="2.2"/>''',
    # --- メッシュ・解析 ---
    "mesh": _hex_mesh(),
    "mesh_show": f'''<path d="M4 19.5V6.5h9.5a6.5 6.5 0 0 1 6.5 6.5v6.5z" fill="{ACC_FILL}" stroke="none"/>
<path d="M4 19.5L9 6.5M9 19.5l4.5-13M14 19.5l3.8-9.5M4 12h13M4 15.5h15" stroke="{ACC}" stroke-width="1"/>
<path d="M4 19.5V6.5h9.5a6.5 6.5 0 0 1 6.5 6.5v6.5z"/>''',
    "open_folder": f'''<path d="M3 19V5.5a1 1 0 0 1 1-1h5l2 2.2h9a1 1 0 0 1 1 1V19a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/>
<path d="M9.5 16.5l6.5-6.5M11.5 10H16v4.5" stroke="{ACC}" stroke-width="1.9"/>''',
    "run": f'<path d="M7 4.5v15l12.5-7.5z" fill="{GREEN}" stroke="#15803d"/>',
    "stop": f'<rect x="5" y="5" width="14" height="14" rx="2" fill="{RED}" stroke="#b91c1c"/>',
    "cancel": f'<circle cx="12" cy="12" r="8.5"/><path d="M8.7 8.7l6.6 6.6M15.3 8.7l-6.6 6.6" stroke="{RED}" stroke-width="2"/>',
    "post": f'''<rect x="4.5" y="3" width="15" height="18" rx="1.5"/><rect x="7" y="5.5" width="10" height="4" fill="{ACC_FILL}" stroke="{ACC}" stroke-width="1.2"/>
<path d="M8 13h2M11 13h2M14 13h2M8 16.5h2M11 16.5h2M14 16.5h2" stroke="{ACC}" stroke-width="1.6"/>''',
    "report": DOC + f'''<path d="M5 17.5l2.5-3 2.5 1.5 3-4" stroke="{ACC}" stroke-width="1.6"/>
<path d="M5 18.5h9" stroke="{INK}" stroke-width="1.1"/>''',
    "open_report": f'''<rect x="2.5" y="3.5" width="19" height="17" rx="1.5"/><path d="M2.5 7.5h19"/>
<path d="M6 16.5l3-3.5 3 2 4-5" stroke="{ACC}" stroke-width="1.7"/>''',
    # --- 結果 ---
    "show_results": f'''<path d="M2 12s3.6-6.5 10-6.5S22 12 22 12s-3.6 6.5-10 6.5S2 12 2 12z"/>
<circle cx="12" cy="12" r="3.4" fill="{ACC}" stroke="none"/><circle cx="13.1" cy="10.9" r="1" fill="#ffffff" stroke="none"/>''',
    "heatmap": _gradient_cells(3, 3, 18, 18, 3, 3)
               + f'<rect x="3" y="3" width="18" height="18" rx=".5" stroke="{INK}" stroke-width="1.2"/>',
    "e_lines": f'''<path d="M3 6c4-3 8 3 12 0s5-1 6 0M3 12c4-3 8 3 12 0s5-1 6 0M3 18c4-3 8 3 12 0s5-1 6 0" stroke="#8a2be2" stroke-width="1.7"/>''',
    "arrows": f'''<path d="M3.5 20.5l6-6M7 14.5h2.5V17M10 11l6-6M13.5 5H16v2.5M14.5 20.5l6-6M18 14.5h2.5V17" stroke="{ACC}" stroke-width="1.8"/>''',
    "e_wall": f'''<path d="M4 19.5V6.5h9.5a6.5 6.5 0 0 1 6.5 6.5v6.5" stroke="{INK}" stroke-width="2"/>
<path d="M4 9.5h4M6.5 8L8 9.5 6.5 11M4 15.5h4M6.5 14L8 15.5 6.5 17M13.5 6.5v4M12 9l1.5 1.5L15 9" stroke="{RED}" stroke-width="1.5"/>''',
    "view3d": f'''<path d="M4.5 7.5v9c0 1.7 3.4 3 7.5 3s7.5-1.3 7.5-3v-9"/>
<ellipse cx="12" cy="7.5" rx="7.5" ry="3"/>
<path d="M12 7.5L12 16.5M12 7.5l5.5 2.6" stroke="{ACC}" stroke-width="1.6"/>
<path d="M12 7.5l7.5 0a7.5 3 0 0 1-2 2.6z" fill="{ACC_FILL}" stroke="{ACC}" stroke-width="1.2"/>''',
    "gif": f'''<rect x="2.5" y="4.5" width="19" height="15" rx="1.5"/>
<path d="M5 4.5v15M19 4.5v15M2.5 8h2.5M2.5 12h2.5M2.5 16h2.5M19 8h2.5M19 12h2.5M19 16h2.5" stroke-width="1.2"/>
<path d="M9.5 9v6l5-3z" fill="{ACC}" stroke="none"/>''',
    "field_map": '<rect x="3" y="3" width="18" height="18" rx="1"/>' + "".join(
        f'<path d="M{x - 2.2} {y}h4.2M{x + 0.6} {y - 1.5}l1.5 1.5-1.5 1.5" stroke="{ACC}" stroke-width="1.4"/>'
        for x in (7.5, 12, 16.5) for y in (7.5, 12, 16.5)),
    "png": f'''<rect x="3" y="3.5" width="18" height="17" rx="1.5"/><circle cx="8.5" cy="9" r="2" fill="{ACC}" stroke="none"/>
<path d="M3.5 18l5.5-6 4 4 3-3 5 5" stroke="{ACC}" stroke-width="1.5"/>''',
    "open_result": f'''<path d="M6 2.8h8.2L19 7.6v13.6H6z"/><path d="M14 2.8V7.6h5"/>
<path d="M7.8 18.2c2.3 0 2.9-1 3.5-3.8S12.4 10 13 10s.9 1.6 1.5 4.4.9 3.8 2.8 3.8" stroke="{ACC}" stroke-width="1.6"/>''',
    # --- 表示 ---
    "grid": f'''<path d="M3 8h18M3 12h18M3 16h18M8 3v18M12 3v18M16 3v18" stroke="{MUTED}" stroke-width="1.2"/>
<rect x="3" y="3" width="18" height="18" rx=".5"/>''',
    "point_labels": f'''<circle cx="7" cy="16" r="2.6" fill="{ACC}" stroke="none"/><circle cx="17" cy="8" r="2.6" fill="{ACC}" stroke="none"/>
<path d="M7 16L17 8" stroke="{ACC}" stroke-width="1.6"/>
<path d="M10 20.5v-5.5l-1.5 1.2M18.5 3.5h3.5l-3 5h3" stroke="{INK}" stroke-width="1.4"/>''',
    "bc_colors": f'''<path d="M4 19.5V6.5h9.5a6.5 6.5 0 0 1 6.5 6.5v6.5" stroke="{MUTED}" stroke-width="1.2"/>
<path d="M4 6.5h9.5" stroke="{BC['pec']}" stroke-width="2.6"/><path d="M4 19.5V6.5" stroke="{BC['eshort']}" stroke-width="2.6"/>
<path d="M20 13v6.5" stroke="{BC['mshort']}" stroke-width="2.6"/><path d="M4 19.5h16" stroke="{BC['none']}" stroke-width="2.2" stroke-dasharray="2.4 2"/>''',
    "axis_range": f'''<path d="M3 4v16M21 4v16" stroke-width="1.8"/><path d="M6 12h12M8.5 9.5L6 12l2.5 2.5M15.5 9.5L18 12l-2.5 2.5" stroke="{ACC}" stroke-width="1.5"/>''',
    "reset_layout": _history_arrow(ACC, 12, 12, 9.2) + '''<rect x="8" y="8.5" width="8" height="7" rx=".8" stroke-width="1.3"/>
<path d="M8 10.5h8M10.5 10.5v5" stroke-width="1.2"/>''',
}


def used_names() -> list[str]:
    """出荷するアイコン名（ACTION_ICONS に現れるもの。パッケージが import できなければ全部）."""
    try:
        sys.path.insert(0, str(ROOT / "src"))
        from axicavity_fem.gui.ui.icon_set import ACTION_ICONS
        names = sorted(set(ACTION_ICONS.values()))
    except Exception:
        names = sorted(ICONS)
    missing = [n for n in names if n not in ICONS]
    if missing:
        raise SystemExit(f"ICONS に無いアイコン名: {missing}")
    return names


def write_icons(out: Path, names: list[str] | None = None) -> int:
    out.mkdir(parents=True, exist_ok=True)
    names = used_names() if names is None else names
    for stale in out.glob("*.svg"):
        if stale.stem not in names:
            stale.unlink()
    for name in names:
        (out / f"{name}.svg").write_text(HEAD.format(ink=INK) + ICONS[name].replace("\n", "") + "</svg>\n",
                                         encoding="utf-8", newline="\n")
    return len(names)


def write_sheet(src: Path, dst: Path, names: list[str]) -> None:
    """確認用の一覧（18 / 24 / 48 px と名前）."""
    from PySide6 import QtCore, QtGui, QtSvg, QtWidgets

    app = QtWidgets.QApplication.instance() or QtWidgets.QApplication(sys.argv[:1])   # noqa: F841
    cols, cell_w, cell_h = 8, 132, 96
    rows = (len(names) + cols - 1) // cols
    image = QtGui.QImage(cols * cell_w, rows * cell_h, QtGui.QImage.Format_ARGB32)
    image.fill(QtGui.QColor("#ffffff"))
    painter = QtGui.QPainter(image)
    painter.setRenderHint(QtGui.QPainter.Antialiasing)
    font = painter.font()
    font.setPointSize(8)
    painter.setFont(font)
    for k, name in enumerate(names):
        r, c = divmod(k, cols)
        x0, y0 = c * cell_w, r * cell_h
        renderer = QtSvg.QSvgRenderer(str(src / f"{name}.svg"))
        renderer.render(painter, QtCore.QRectF(x0 + 8, y0 + 10, 18, 18))
        renderer.render(painter, QtCore.QRectF(x0 + 8, y0 + 34, 24, 24))
        renderer.render(painter, QtCore.QRectF(x0 + 50, y0 + 8, 48, 48))
        painter.setPen(QtGui.QColor("#475569"))
        painter.drawText(QtCore.QRectF(x0, y0 + 66, cell_w, 20), QtCore.Qt.AlignCenter, name)
    painter.end()
    image.save(str(dst))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="リボンのアイコン（SVG）を書き出す")
    parser.add_argument("--out", type=Path, default=ICON_DIR, help="書き出し先（既定: gui/ui/icons）")
    parser.add_argument("--sheet", type=Path, help="確認用の一覧画像（PNG）も作る")
    args = parser.parse_args(argv)
    names = used_names()
    count = write_icons(args.out, names)
    print(f"{count} icons -> {args.out}")
    if args.sheet:
        write_sheet(args.out, args.sheet, names)
        print(f"sheet -> {args.sheet}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
